### ISSUE TITLE
[Suggestion] Twitch VOD implementation

### ISSUE THREAD

**Issue by JJdelete** [trmcnvn/twitch-chat-overlay#22]
Is there any plans to implement TCO so that it could be used for viewing Twitch VODs as well as live streams?

**Comment by Eric-01** [comment]
I think your feature request is already covered by #6, and it was previously added to the "TODO" list, so I suppose there are plans to implement this. However, as far as I know, adding a VOD chat functionality is much harder to implement than a livestream chat, since the livestream chat is easily accessible via the following link: `https://www.twitch.tv/popout/<streamer_name>/chat`, while the VOD chat isn't.
